import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {once} from 'node:events';
import {createApp} from '../server.mjs';
import {draftToItem,makePlan,draftSchema,batchBlindPrompt,generationPrompt} from '../model-v2.mjs';
import {schemaErrors,validateItem} from '../validation.mjs';
import {evaluationReport} from '../learning.mjs';
const curriculum=JSON.parse(fs.readFileSync(new URL('../curriculum.json',import.meta.url)));
const draft=()=>({title:'Test-only closed circuit question',family:'circuit_prediction',difficulty:'Medium',skill:'Application',context:'One working battery and bulb are connected in one loop with a switch. All wire contacts are secure. The switch is open.',question:'Which change completes the conducting loop?',table:{columns:[],rows:[]},options:[{id:1,text:'Close the switch.'},{id:2,text:'Remove the battery.'},{id:3,text:'Remove the bulb.'},{id:4,text:'Leave the switch open.'}],answer:{optionId:1,explanation:'Closing the switch completes the conducting path.',steps:['An open switch breaks the path.','Closing it completes the loop.'],distractors:[{optionId:2,reason:'The circuit requires the battery.'},{optionId:3,reason:'Removing the bulb breaks the loop.'},{optionId:4,reason:'The path remains broken.'}]},mappings:[{objectiveId:'P5-ELEC-CLOSED',evidence:'The pupil identifies how to close the loop.'}],design:{reasoningTask:'Predict effect of closing a switch',requiredKnowledge:['A closed loop permits current.'],originalityRationale:'Test fixture, not an originality assertion.'}});
const approval=v=>({version:v,action:'approved',reviewer:'TEST ONLY',note:'Simulated test assertion only.',attestations:{science:true,alignment:true,originality:true,difficulty:true},reviewSeconds:90,issueCodes:[]});
async function setup(t,extra={}){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'simcc-v2-test-'));const prompts=[];
 const app=createApp({dataDir:dir,providerStatus:()=>['replay','codex'].map(id=>({id,available:true,label:id})),runStructured:async(provider,prompt,schema)=>{prompts.push({prompt,schema});if(schema==='draft-schema.json'){const payload=JSON.parse(prompt.split('\n\n').at(-1));return {value:{questions:payload.plan.map(p=>({...draft(),family:p.family,difficulty:p.difficulty}))},model:'mock-test',usage:{tokens:1},durationMs:1};}const q=JSON.parse(prompt.slice(prompt.indexOf('\n')+1)).questions;return {value:{reviews:q.map(x=>({id:x.id,optionId:1,reasoning:'Fixture independent solve',issues:[]}))},model:'mock-test',usage:{tokens:1},durationMs:1};},...extra});
 app.server.listen(0,'127.0.0.1');await once(app.server,'listening');t.after(async()=>{app.server.closeAllConnections();await new Promise(r=>app.server.close(r));fs.rmSync(dir,{recursive:true,force:true});});
 const base='http://127.0.0.1:'+app.server.address().port;
 const call=async(route,body,method)=>{const r=await fetch(base+route,{method:method||(body?'POST':'GET'),headers:{'Content-Type':'application/json','X-CSRF-Token':app.csrfToken},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};};
 const batch=async(count=1)=>{const start=await call('/api/batches',{provider:'codex',count,family:'balanced',difficulty:'Mixed'});assert.equal(start.status,202);for(let i=0;i<300;i++){const r=await call('/api/jobs/'+start.data.jobId);if(['completed','failed'].includes(r.data.status))return (await call('/api/evaluations')).data.batches.find(b=>b.id===start.data.batchId);await new Promise(r=>setTimeout(r,5));}throw new Error('timeout');};
 return {...app,call,batch,prompts};
}

test('v2 schema accepts a single relevant learning objective and never applies legacy proof',()=>{const d=draft();assert.deepEqual(schemaErrors({questions:[d]},draftSchema),[]);const r=validateItem(draftToItem(d,curriculum));assert.equal(r.blocking,0,JSON.stringify(r.results));assert.equal(r.results.find(x=>x.id==='circuit_logic').status,'not_run');});
test('v2 malformed table is blocked, even with a valid JSON shape',()=>{const d=draft();d.table={columns:['A','B'],rows:[['one cell']]};const r=validateItem(draftToItem(d,curriculum));assert.ok(r.results.some(x=>x.id==='data_table'&&x.status==='fail'));});
test('generation planning covers five reasoning families; blind input excludes keys and design',()=>{const plan=makePlan(10);assert.equal(new Set(plan.map(p=>p.family)).size,5);const item=draftToItem(draft(),curriculum);item.answer.explanation_en='SECRET_KEY';item.design.originalityRationale='SECRET_DESIGN';const prompt=batchBlindPrompt([{id:'x',item}],curriculum);assert.ok(!prompt.includes('SECRET_'));assert.match(generationPrompt(plan,curriculum),/Do NOT imitate/);assert.throws(()=>makePlan(100));});
test('ten-slot pipeline stores every attempt, runs actual injected blind stage and leaves human rates null',async t=>{const a=await setup(t);const report=await a.batch(10);assert.equal(report.status,'completed');assert.equal(report.metrics.generated,10);assert.equal(report.metrics.blindAgreed,10);assert.equal(report.metrics.humanAcceptanceRate,null);assert.equal(report.metrics.averageReviewSeconds,null);assert.equal(a.prompts.length,2);assert.equal(a.store.all().filter(r=>r.status==='approved').length,0);});
test('failed generation is retained without replay or a fabricated acceptance rate',async t=>{const a=await setup(t,{runStructured:async()=>{throw new Error('private diagnostic');}});const b=await a.batch(5);assert.equal(b.status,'failed');assert.equal(b.rows.length,5);assert.equal(b.metrics.generationFailed,5);assert.equal(b.metrics.generated,0);assert.ok(!b.error.includes('private'));assert.equal(a.store.all().length,1);});
test('missing blind stage blocks v2 approval and stays visible in report',async t=>{const a=await setup(t,{runStructured:async(p,prompt,schema)=>{if(schema==='batch-blind-schema.json')throw new Error('offline');const d=draft();d.family='material_inference';d.difficulty='Easy';return {value:{questions:[d]},model:'test'};}});const b=await a.batch();const id=b.rows[0].recordId;assert.ok(id);assert.equal(b.metrics.blindCompleted,0);assert.equal((await a.call('/api/records/'+id+'/review',approval(1))).status,409);});
test('academic correction records old/new labels, withdraws approval and invalidates blind solve',async t=>{const a=await setup(t);const b=await a.batch();const id=b.rows[0].recordId;assert.equal((await a.call('/api/records/'+id+'/review',approval(1))).status,200);const corrected=await a.call('/api/records/'+id+'/labels',{version:1,reviewer:'Test teacher',note:'Single closed-circuit objective is sufficient; difficulty revised.',difficulty:'Hard',skill:'Application',objectives:['P5-ELEC-CLOSED']});assert.equal(corrected.status,200,JSON.stringify(corrected.data));const r=corrected.data.record;assert.equal(r.version,2);assert.equal(r.status,'draft');assert.equal(r.blindReview,null);assert.equal(r.labels.difficulty,'Hard');assert.equal(r.reviewEvents.at(-1).before.difficulty,'Easy');assert.equal(r.reviewEvents.at(-1).after.difficulty,'Hard');assert.equal((await a.call('/api/practice/config')).data.available,0);assert.equal((await a.call('/api/feedback/export')).data.records.length,1);});
test('practice serves approved filtered questions without keys; submit reveals explanations and grades once',async t=>{const a=await setup(t);const b=await a.batch();const id=b.rows[0].recordId;assert.equal((await a.call('/api/practice/start',{count:1})).status,404);await a.call('/api/records/'+id+'/review',approval(1));const s=await a.call('/api/practice/start',{count:5,difficulty:'Easy',objective:'P5-ELEC-CLOSED'});assert.equal(s.status,200);assert.equal(s.data.returned,1);assert.ok(!JSON.stringify(s.data).includes('explanation'));assert.ok(!JSON.stringify(s.data).includes('option_id'));const answer={answers:{[id]:1}};const r=await a.call('/api/practice/'+s.data.sessionId+'/submit',answer);assert.equal(r.data.correct,1);assert.ok(r.data.items[0].answer.explanation_en);assert.deepEqual((await a.call('/api/practice/'+s.data.sessionId+'/submit',answer)).data,r.data);assert.equal((await a.call('/api/practice/'+s.data.sessionId+'/submit',{answers:{[id]:2}})).status,409);});
test('editing an approved question invalidates already opened practice sessions',async t=>{const a=await setup(t);const b=await a.batch();const id=b.rows[0].recordId;await a.call('/api/records/'+id+'/review',approval(1));const s=await a.call('/api/practice/start',{count:1});const item=a.store.get(id).item;await a.call('/api/records/'+id,{version:1,item},'PUT');assert.equal((await a.call('/api/practice/'+s.data.sessionId+'/submit',{answers:{[id]:1}})).data.code,'PRACTICE_STALE');});
test('recorded practice demo never populates the approved bank or review metrics',async t=>{const a=await setup(t);const s=await a.call('/api/practice/start',{count:1,demo:true});assert.equal(s.data.demo,true);const id=s.data.questions[0].id;const r=await a.call('/api/practice/'+s.data.sessionId+'/submit',{answers:{[id]:3}});assert.equal(r.data.correct,1);assert.equal((await a.call('/api/practice/config')).data.available,0);assert.equal((await a.call('/api/export')).data.records.length,0);});
test('human timing uses actual reported minutes and acceptance excludes pending items',async t=>{const a=await setup(t);const b=await a.batch(5);await a.call('/api/records/'+b.rows[0].recordId+'/review',approval(1));await a.call('/api/records/'+b.rows[1].recordId+'/review',{...approval(1),action:'changes_requested',reviewSeconds:30,issueCodes:['difficulty']});const report=(await a.call('/api/evaluations')).data.batches[0];assert.equal(report.metrics.humanAcceptanceRate,0.5);assert.equal(report.metrics.averageReviewSeconds,60);assert.equal(report.metrics.reviewSecondsPerApproved,120);});

test('an automatically withdrawn approval is excluded from current acceptance',()=>{
 const batch={plan:[{index:1}],entries:[{index:1,recordId:'withdrawn',initialLocalBlocking:0}]};
 const record={id:'withdrawn',version:1,status:'changes_requested',item:{question_family:'circuit_prediction'},labels:{difficulty:'Medium'},checks:{blocking:1},reviewEvents:[{version:1,action:'approved',reviewSeconds:60},{version:1,action:'review_disagreement'}]};
 const report=evaluationReport(batch,[record]);
 assert.equal(report.metrics.humanReviewed,1);
 assert.equal(report.metrics.humanApproved,0);
 assert.equal(report.metrics.humanAcceptanceRate,0);
 assert.equal(report.metrics.reviewSecondsPerApproved,null);
});
